name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: install gettext on Ubuntu
        if: runner.os == 'Linux'
        run: |
          set -eux -o pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gettext
      - name: Install gettext on macOS
        if: runner.os == 'macOS'
        run: |
          set -eux -o pipefail
          brew install gettext
          echo /usr/local/opt/gettext/bin >> "$GITHUB_PATH"
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: git version
